# Generated by Django 2.2 on 2019-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190701_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentor',
            old_name='family',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='commentor',
            old_name='name',
            new_name='last_name',
        ),
    ]
