# Generated by Django 2.2 on 2019-05-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('identificationcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('telephonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('vote', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wallet', models.DecimalField(decimal_places=3, max_digits=13)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Deactive')], max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('S', 'Staff'), ('C', 'Customer'), ('M', 'Mechanic')], max_length=50, null=True)),
                ('password', models.CharField(max_length=50)),
                ('addresses', models.ManyToManyField(blank=True, to='users.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('licenseplate', models.CharField(max_length=8)),
                ('type', models.CharField(blank=True, choices=[('A', 'Type A'), ('B', 'Type B')], max_length=50, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
        ),
    ]
