# Generated by Django 2.2 on 2019-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('enddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('totalprice', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bankname', models.CharField(max_length=50)),
                ('cardnumber', models.CharField(max_length=16)),
                ('refrencenumber', models.CharField(max_length=50)),
                ('issuenumber', models.CharField(max_length=50)),
                ('terminalnumber', models.CharField(max_length=50)),
                ('transactionnumber', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Deactive')], max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('S', 'Staff'), ('C', 'Customer'), ('M', 'Mechanic')], max_length=50, null=True)),
            ],
        ),
    ]
