# Generated by Django 2.1.5 on 2019-02-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=50)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('Vote', models.PositiveSmallIntegerField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('LicensePlate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MotorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EndDate', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('TotalPrice', models.DecimalField(decimal_places=3, max_digits=13)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RequestGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Good')),
                ('Request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('BankName', models.CharField(max_length=50)),
                ('CardNumber', models.CharField(max_length=16)),
                ('RefrenceNumber', models.CharField(max_length=50)),
                ('IssueNumber', models.CharField(max_length=50)),
                ('TerminalNumber', models.CharField(max_length=50)),
                ('TransactionNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('IdentificationCode', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('TelephoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('JoinedDate', models.DateTimeField(auto_now_add=True)),
                ('Picture', models.ImageField(upload_to='')),
                ('Vote', models.PositiveSmallIntegerField()),
                ('Wallet', models.DecimalField(decimal_places=3, max_digits=13)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserStatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TransactionStatus'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TransactionType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User'),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Service'),
        ),
        migrations.AddField(
            model_name='request',
            name='Mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='Motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Motor'),
        ),
        migrations.AddField(
            model_name='motor',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User'),
        ),
        migrations.AddField(
            model_name='motor',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MotorType'),
        ),
    ]
