# Generated by Django 2.1.7 on 2019-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190326_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_image',
            name='Good',
        ),
        migrations.RemoveField(
            model_name='good_image',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='requestgood',
            name='Good',
        ),
        migrations.RemoveField(
            model_name='requestgood',
            name='Request',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='Request',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='Service',
        ),
        migrations.AddField(
            model_name='good',
            name='Images',
            field=models.ManyToManyField(to='core.Image'),
        ),
        migrations.AddField(
            model_name='request',
            name='Goods',
            field=models.ManyToManyField(to='core.Good'),
        ),
        migrations.AddField(
            model_name='request',
            name='Services',
            field=models.ManyToManyField(to='core.Service'),
        ),
        migrations.DeleteModel(
            name='Good_Image',
        ),
        migrations.DeleteModel(
            name='RequestGood',
        ),
        migrations.DeleteModel(
            name='RequestService',
        ),
    ]
