# Generated by Django 2.1.7 on 2019-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190504_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='Images',
            field=models.ManyToManyField(blank=True, to='core.Image'),
        ),
    ]
